services:
  blockchain:
    image:  ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    networks:
      - "sistema-eleitoral"
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    entrypoint: ["anvil"]
    
  deployer:
    build: ./smart-contracts
    networks:
      - "sistema-eleitoral"
      
    depends_on:
      - "blockchain"
    command: npm run deploy:local
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - "sistema-eleitoral"
    volumes:
      - mongodb-data:/data/db
  
  server:
    build: ./server
    env_file:
      - ./server/.env
      
    networks:
      - "sistema-eleitoral"
    depends_on:
      - "mongodb"
      - "deployer"
    ports:
      - "8080:8080"
    command: npm run start
  client:
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - server_url=${VITE_SERVER_URL}
        - sistema_eleitoral_contract_address=${VITE_SISTEMA_ELEITORAL_CONTRACT_ADDRESS}
        - eth_node_url=${VITE_ETH_NODE_URL}
    networks:
      - "sistema-eleitoral"
    ports:
      - "3000:3000"
    command: npm run start
    
networks:
  sistema-eleitoral:

volumes:
  mongodb-data:
    