services:
  blockchain:
    image:  ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    networks:
      - "sistema-eleitoral"
    volumes:
      - anvil:/anvil
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    entrypoint: ["anvil"]
    
  deployer:
    build: ./smart-contracts
    networks:
      - "sistema-eleitoral"
      
    depends_on:
      - "blockchain"
    command: npm run deploy:local
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - "sistema-eleitoral"
    volumes:
      - mongodb-data:/data/db
  
  server:
    build: ./server
    env_file:
      - ./server/.env
      
    networks:
      - "sistema-eleitoral"
    depends_on:
      - "mongodb"
      - "deployer"
    ports:
      - "8080:8080"
    command: npm run start
    
networks:
  sistema-eleitoral:

volumes:
  mongodb-data:
  anvil:
    