name: Testando Smart Contracts da Eleição

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test-smart-contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Instalar Pacotes
        run:  cd ./smart-contracts && npm ci
      - name: Compilar Smart Contracts
        run:  cd ./smart-contracts && npm run compile
      - name: Executar Testes
        run:  cd ./smart-contracts && npm run test

      